---
- name: Configure apt sources
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '644'
  register: common_apt_sources

- name: Update apt package information
  apt:
    update_cache: true
  when: common_apt_sources is changed
  tags: skip_ansible_lint
