---
- name: Disable and stop systemd-resolved
  systemd:
    name: systemd-resolved.service
    state: stopped
    enabled: false
    masked: true
  when: (common_systemd_resolved_enabled is defined
        and not common_systemd_resolved_enabled)

- name: Configure systemd-resolved
  block:

    - name: Configure systemd-resolved
      template:
        src: resolved.conf.j2
        dest: /etc/systemd/resolved.conf
        owner: root
        group: root
        mode: '644'
      register: resolved_conf

    - name: Stop systemd-resolved
      systemd:
        name: systemd-resolved.service
        state: stopped
      when: resolved_conf is changed

    - name: Make sure systemd-resolved is enabled
      systemd:
        name: systemd-resolved.service
        enabled: true
        masked: false

    - name: Make sure systemd-resolved is started
      systemd:
        name: systemd-resolved.service
        state: started

  when: (common_systemd_resolved_enabled is defined
        and common_systemd_resolved_enabled)
