---
- name: generate locales
  command: locale-gen

- name: restart cron
  service:
    name: cron
    state: restarted

- name: update tzdata
  command: dpkg-reconfigure -f noninteractive tzdata

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved.service
    state: restarted

- name: restart systemd-timesyncd
  systemd:
    name: systemd-timesyncd.service
    state: restarted
