---
- name: Converge
  hosts: all

  tasks:
    - name: Create /etc/default/motd-news files and services
      apt:
        name:
          - base-files
          - motd-news-config
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: "Include ansible-role-common"
      include_role:
        name: "common"
